stages:
  - build
  - publish

#--------------------------
# Build templates
#--------------------------

.build-template: &build-template_definition
  stage: build
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
    - tree ${CI_JOB_NAME}
  variables:
    BRANCH: ${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

#--------------------------
# Build jobs
#--------------------------

cc7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  <<: *build-template_definition

centos8:
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  <<: *build-template_definition

cs9:
  image: gitlab-registry.cern.ch/linuxsupport/cs9-base
  <<: *build-template_definition

fedora-36:
  image: fedora:36
  <<: *build-template_definition

fedora-37:
  image: fedora:37
  <<: *build-template_definition

fedora-rawhide:
  image: fedora:rawhide
  <<: *build-template_definition
  allow_failure: true
  when: manual

#--------------------------
# Publish templates
#--------------------------

.publish-template: &publish-template_definition
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - cc7
    - centos8
    - cs9
    - fedora-36
    - fedora-37
    - fedora-rawhide
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - eosfusebind
    - |
        for platform in cc7 centos8 cs9 fedora-36 fedora-37 fedora-rawhide; do
          if [[ "${platform}" == "fedora-rawhide" ]] && [[ ! -d ${platform} ]] ; then
            echo "Skipping ${platform} packages..." ;
            continue ;
          fi
          packaging/gfal2-repo-manager.py --action add --base /eos/project/d/dmc/www/repos/ --ref ${CI_COMMIT_REF_NAME} --packages ${platform}/RPMS/*/*.rpm ${platform}/SRPMS/*
        done
    - sleep 60
  tags:
    - docker-privileged
  retry: 2

#--------------------------
# Publish jobs
#--------------------------

rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "dmc"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_TAG != null'
    - if: '$CI_COMMIT_REF_NAME != "develop" && $CI_COMMIT_TAG == null'
      when: manual
