/* srmv2Client.c
   Generated by gSOAP 2.7.6b from srm.v2.2.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "srmv2H.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) srmv2Client.c ver 2.7.6b 2010-04-29 07:52:06 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmReserveSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmReserveSpaceRequest *srmReserveSpaceRequest, struct srm2__srmReserveSpaceResponse_ *_param_1)
{	struct srm2__srmReserveSpace soap_tmp_srm2__srmReserveSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmReserveSpace.srmReserveSpaceRequest = srmReserveSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReserveSpace(soap, &soap_tmp_srm2__srmReserveSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmReserveSpace(soap, &soap_tmp_srm2__srmReserveSpace, "srm2:srmReserveSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReserveSpace(soap, &soap_tmp_srm2__srmReserveSpace, "srm2:srmReserveSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmReserveSpaceResponse_(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmReserveSpaceResponse_(soap, _param_1, "srm2:srmReserveSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfReserveSpaceRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfReserveSpaceRequestRequest *srmStatusOfReserveSpaceRequestRequest, struct srm2__srmStatusOfReserveSpaceRequestResponse_ *_param_2)
{	struct srm2__srmStatusOfReserveSpaceRequest soap_tmp_srm2__srmStatusOfReserveSpaceRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfReserveSpaceRequest.srmStatusOfReserveSpaceRequestRequest = srmStatusOfReserveSpaceRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfReserveSpaceRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfReserveSpaceRequest, "srm2:srmStatusOfReserveSpaceRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfReserveSpaceRequest, "srm2:srmStatusOfReserveSpaceRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfReserveSpaceRequestResponse_(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfReserveSpaceRequestResponse_(soap, _param_2, "srm2:srmStatusOfReserveSpaceRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmReleaseSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmReleaseSpaceRequest *srmReleaseSpaceRequest, struct srm2__srmReleaseSpaceResponse_ *_param_3)
{	struct srm2__srmReleaseSpace soap_tmp_srm2__srmReleaseSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmReleaseSpace.srmReleaseSpaceRequest = srmReleaseSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReleaseSpace(soap, &soap_tmp_srm2__srmReleaseSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmReleaseSpace(soap, &soap_tmp_srm2__srmReleaseSpace, "srm2:srmReleaseSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReleaseSpace(soap, &soap_tmp_srm2__srmReleaseSpace, "srm2:srmReleaseSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmReleaseSpaceResponse_(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmReleaseSpaceResponse_(soap, _param_3, "srm2:srmReleaseSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmUpdateSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmUpdateSpaceRequest *srmUpdateSpaceRequest, struct srm2__srmUpdateSpaceResponse_ *_param_4)
{	struct srm2__srmUpdateSpace soap_tmp_srm2__srmUpdateSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmUpdateSpace.srmUpdateSpaceRequest = srmUpdateSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmUpdateSpace(soap, &soap_tmp_srm2__srmUpdateSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmUpdateSpace(soap, &soap_tmp_srm2__srmUpdateSpace, "srm2:srmUpdateSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmUpdateSpace(soap, &soap_tmp_srm2__srmUpdateSpace, "srm2:srmUpdateSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmUpdateSpaceResponse_(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmUpdateSpaceResponse_(soap, _param_4, "srm2:srmUpdateSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfUpdateSpaceRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfUpdateSpaceRequestRequest *srmStatusOfUpdateSpaceRequestRequest, struct srm2__srmStatusOfUpdateSpaceRequestResponse_ *_param_5)
{	struct srm2__srmStatusOfUpdateSpaceRequest soap_tmp_srm2__srmStatusOfUpdateSpaceRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfUpdateSpaceRequest.srmStatusOfUpdateSpaceRequestRequest = srmStatusOfUpdateSpaceRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfUpdateSpaceRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfUpdateSpaceRequest, "srm2:srmStatusOfUpdateSpaceRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_srm2__srmStatusOfUpdateSpaceRequest, "srm2:srmStatusOfUpdateSpaceRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfUpdateSpaceRequestResponse_(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfUpdateSpaceRequestResponse_(soap, _param_5, "srm2:srmStatusOfUpdateSpaceRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetSpaceMetaData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetSpaceMetaDataRequest *srmGetSpaceMetaDataRequest, struct srm2__srmGetSpaceMetaDataResponse_ *_param_6)
{	struct srm2__srmGetSpaceMetaData soap_tmp_srm2__srmGetSpaceMetaData;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetSpaceMetaData.srmGetSpaceMetaDataRequest = srmGetSpaceMetaDataRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetSpaceMetaData(soap, &soap_tmp_srm2__srmGetSpaceMetaData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetSpaceMetaData(soap, &soap_tmp_srm2__srmGetSpaceMetaData, "srm2:srmGetSpaceMetaData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetSpaceMetaData(soap, &soap_tmp_srm2__srmGetSpaceMetaData, "srm2:srmGetSpaceMetaData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetSpaceMetaDataResponse_(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetSpaceMetaDataResponse_(soap, _param_6, "srm2:srmGetSpaceMetaDataResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmChangeSpaceForFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmChangeSpaceForFilesRequest *srmChangeSpaceForFilesRequest, struct srm2__srmChangeSpaceForFilesResponse_ *_param_7)
{	struct srm2__srmChangeSpaceForFiles soap_tmp_srm2__srmChangeSpaceForFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmChangeSpaceForFiles.srmChangeSpaceForFilesRequest = srmChangeSpaceForFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmChangeSpaceForFiles(soap, &soap_tmp_srm2__srmChangeSpaceForFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmChangeSpaceForFiles(soap, &soap_tmp_srm2__srmChangeSpaceForFiles, "srm2:srmChangeSpaceForFiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmChangeSpaceForFiles(soap, &soap_tmp_srm2__srmChangeSpaceForFiles, "srm2:srmChangeSpaceForFiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmChangeSpaceForFilesResponse_(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmChangeSpaceForFilesResponse_(soap, _param_7, "srm2:srmChangeSpaceForFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfChangeSpaceForFilesRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfChangeSpaceForFilesRequestRequest *srmStatusOfChangeSpaceForFilesRequestRequest, struct srm2__srmStatusOfChangeSpaceForFilesRequestResponse_ *_param_8)
{	struct srm2__srmStatusOfChangeSpaceForFilesRequest soap_tmp_srm2__srmStatusOfChangeSpaceForFilesRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfChangeSpaceForFilesRequest.srmStatusOfChangeSpaceForFilesRequestRequest = srmStatusOfChangeSpaceForFilesRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_srm2__srmStatusOfChangeSpaceForFilesRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_srm2__srmStatusOfChangeSpaceForFilesRequest, "srm2:srmStatusOfChangeSpaceForFilesRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_srm2__srmStatusOfChangeSpaceForFilesRequest, "srm2:srmStatusOfChangeSpaceForFilesRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfChangeSpaceForFilesRequestResponse_(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfChangeSpaceForFilesRequestResponse_(soap, _param_8, "srm2:srmStatusOfChangeSpaceForFilesRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmExtendFileLifeTimeInSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmExtendFileLifeTimeInSpaceRequest *srmExtendFileLifeTimeInSpaceRequest, struct srm2__srmExtendFileLifeTimeInSpaceResponse_ *_param_9)
{	struct srm2__srmExtendFileLifeTimeInSpace soap_tmp_srm2__srmExtendFileLifeTimeInSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmExtendFileLifeTimeInSpace.srmExtendFileLifeTimeInSpaceRequest = srmExtendFileLifeTimeInSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_srm2__srmExtendFileLifeTimeInSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_srm2__srmExtendFileLifeTimeInSpace, "srm2:srmExtendFileLifeTimeInSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_srm2__srmExtendFileLifeTimeInSpace, "srm2:srmExtendFileLifeTimeInSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmExtendFileLifeTimeInSpaceResponse_(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmExtendFileLifeTimeInSpaceResponse_(soap, _param_9, "srm2:srmExtendFileLifeTimeInSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmPurgeFromSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmPurgeFromSpaceRequest *srmPurgeFromSpaceRequest, struct srm2__srmPurgeFromSpaceResponse_ *_param_10)
{	struct srm2__srmPurgeFromSpace soap_tmp_srm2__srmPurgeFromSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmPurgeFromSpace.srmPurgeFromSpaceRequest = srmPurgeFromSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPurgeFromSpace(soap, &soap_tmp_srm2__srmPurgeFromSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmPurgeFromSpace(soap, &soap_tmp_srm2__srmPurgeFromSpace, "srm2:srmPurgeFromSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPurgeFromSpace(soap, &soap_tmp_srm2__srmPurgeFromSpace, "srm2:srmPurgeFromSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmPurgeFromSpaceResponse_(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmPurgeFromSpaceResponse_(soap, _param_10, "srm2:srmPurgeFromSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetSpaceTokens(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetSpaceTokensRequest *srmGetSpaceTokensRequest, struct srm2__srmGetSpaceTokensResponse_ *_param_11)
{	struct srm2__srmGetSpaceTokens soap_tmp_srm2__srmGetSpaceTokens;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetSpaceTokens.srmGetSpaceTokensRequest = srmGetSpaceTokensRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetSpaceTokens(soap, &soap_tmp_srm2__srmGetSpaceTokens);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetSpaceTokens(soap, &soap_tmp_srm2__srmGetSpaceTokens, "srm2:srmGetSpaceTokens", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetSpaceTokens(soap, &soap_tmp_srm2__srmGetSpaceTokens, "srm2:srmGetSpaceTokens", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetSpaceTokensResponse_(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetSpaceTokensResponse_(soap, _param_11, "srm2:srmGetSpaceTokensResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmSetPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmSetPermissionRequest *srmSetPermissionRequest, struct srm2__srmSetPermissionResponse_ *_param_12)
{	struct srm2__srmSetPermission soap_tmp_srm2__srmSetPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmSetPermission.srmSetPermissionRequest = srmSetPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmSetPermission(soap, &soap_tmp_srm2__srmSetPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmSetPermission(soap, &soap_tmp_srm2__srmSetPermission, "srm2:srmSetPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmSetPermission(soap, &soap_tmp_srm2__srmSetPermission, "srm2:srmSetPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmSetPermissionResponse_(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmSetPermissionResponse_(soap, _param_12, "srm2:srmSetPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmCheckPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmCheckPermissionRequest *srmCheckPermissionRequest, struct srm2__srmCheckPermissionResponse_ *_param_13)
{	struct srm2__srmCheckPermission soap_tmp_srm2__srmCheckPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmCheckPermission.srmCheckPermissionRequest = srmCheckPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmCheckPermission(soap, &soap_tmp_srm2__srmCheckPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmCheckPermission(soap, &soap_tmp_srm2__srmCheckPermission, "srm2:srmCheckPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmCheckPermission(soap, &soap_tmp_srm2__srmCheckPermission, "srm2:srmCheckPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmCheckPermissionResponse_(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmCheckPermissionResponse_(soap, _param_13, "srm2:srmCheckPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetPermissionRequest *srmGetPermissionRequest, struct srm2__srmGetPermissionResponse_ *_param_14)
{	struct srm2__srmGetPermission soap_tmp_srm2__srmGetPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetPermission.srmGetPermissionRequest = srmGetPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetPermission(soap, &soap_tmp_srm2__srmGetPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetPermission(soap, &soap_tmp_srm2__srmGetPermission, "srm2:srmGetPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetPermission(soap, &soap_tmp_srm2__srmGetPermission, "srm2:srmGetPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetPermissionResponse_(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetPermissionResponse_(soap, _param_14, "srm2:srmGetPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmMkdir(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmMkdirRequest *srmMkdirRequest, struct srm2__srmMkdirResponse_ *_param_15)
{	struct srm2__srmMkdir soap_tmp_srm2__srmMkdir;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmMkdir.srmMkdirRequest = srmMkdirRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmMkdir(soap, &soap_tmp_srm2__srmMkdir);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmMkdir(soap, &soap_tmp_srm2__srmMkdir, "srm2:srmMkdir", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmMkdir(soap, &soap_tmp_srm2__srmMkdir, "srm2:srmMkdir", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmMkdirResponse_(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmMkdirResponse_(soap, _param_15, "srm2:srmMkdirResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmRmdir(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmRmdirRequest *srmRmdirRequest, struct srm2__srmRmdirResponse_ *_param_16)
{	struct srm2__srmRmdir soap_tmp_srm2__srmRmdir;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmRmdir.srmRmdirRequest = srmRmdirRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmRmdir(soap, &soap_tmp_srm2__srmRmdir);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmRmdir(soap, &soap_tmp_srm2__srmRmdir, "srm2:srmRmdir", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmRmdir(soap, &soap_tmp_srm2__srmRmdir, "srm2:srmRmdir", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmRmdirResponse_(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmRmdirResponse_(soap, _param_16, "srm2:srmRmdirResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmRm(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmRmRequest *srmRmRequest, struct srm2__srmRmResponse_ *_param_17)
{	struct srm2__srmRm soap_tmp_srm2__srmRm;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmRm.srmRmRequest = srmRmRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmRm(soap, &soap_tmp_srm2__srmRm);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmRm(soap, &soap_tmp_srm2__srmRm, "srm2:srmRm", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmRm(soap, &soap_tmp_srm2__srmRm, "srm2:srmRm", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmRmResponse_(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmRmResponse_(soap, _param_17, "srm2:srmRmResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmLs(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmLsRequest *srmLsRequest, struct srm2__srmLsResponse_ *_param_18)
{	struct srm2__srmLs soap_tmp_srm2__srmLs;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmLs.srmLsRequest = srmLsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmLs(soap, &soap_tmp_srm2__srmLs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmLs(soap, &soap_tmp_srm2__srmLs, "srm2:srmLs", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmLs(soap, &soap_tmp_srm2__srmLs, "srm2:srmLs", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmLsResponse_(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmLsResponse_(soap, _param_18, "srm2:srmLsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfLsRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfLsRequestRequest *srmStatusOfLsRequestRequest, struct srm2__srmStatusOfLsRequestResponse_ *_param_19)
{	struct srm2__srmStatusOfLsRequest soap_tmp_srm2__srmStatusOfLsRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfLsRequest.srmStatusOfLsRequestRequest = srmStatusOfLsRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfLsRequest(soap, &soap_tmp_srm2__srmStatusOfLsRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfLsRequest(soap, &soap_tmp_srm2__srmStatusOfLsRequest, "srm2:srmStatusOfLsRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfLsRequest(soap, &soap_tmp_srm2__srmStatusOfLsRequest, "srm2:srmStatusOfLsRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfLsRequestResponse_(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfLsRequestResponse_(soap, _param_19, "srm2:srmStatusOfLsRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmMv(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmMvRequest *srmMvRequest, struct srm2__srmMvResponse_ *_param_20)
{	struct srm2__srmMv soap_tmp_srm2__srmMv;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmMv.srmMvRequest = srmMvRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmMv(soap, &soap_tmp_srm2__srmMv);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmMv(soap, &soap_tmp_srm2__srmMv, "srm2:srmMv", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmMv(soap, &soap_tmp_srm2__srmMv, "srm2:srmMv", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmMvResponse_(soap, _param_20);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmMvResponse_(soap, _param_20, "srm2:srmMvResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmPrepareToGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmPrepareToGetRequest *srmPrepareToGetRequest, struct srm2__srmPrepareToGetResponse_ *_param_21)
{	struct srm2__srmPrepareToGet soap_tmp_srm2__srmPrepareToGet;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmPrepareToGet.srmPrepareToGetRequest = srmPrepareToGetRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPrepareToGet(soap, &soap_tmp_srm2__srmPrepareToGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmPrepareToGet(soap, &soap_tmp_srm2__srmPrepareToGet, "srm2:srmPrepareToGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPrepareToGet(soap, &soap_tmp_srm2__srmPrepareToGet, "srm2:srmPrepareToGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmPrepareToGetResponse_(soap, _param_21);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmPrepareToGetResponse_(soap, _param_21, "srm2:srmPrepareToGetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfGetRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfGetRequestRequest *srmStatusOfGetRequestRequest, struct srm2__srmStatusOfGetRequestResponse_ *_param_22)
{	struct srm2__srmStatusOfGetRequest soap_tmp_srm2__srmStatusOfGetRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfGetRequest.srmStatusOfGetRequestRequest = srmStatusOfGetRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfGetRequest(soap, &soap_tmp_srm2__srmStatusOfGetRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfGetRequest(soap, &soap_tmp_srm2__srmStatusOfGetRequest, "srm2:srmStatusOfGetRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfGetRequest(soap, &soap_tmp_srm2__srmStatusOfGetRequest, "srm2:srmStatusOfGetRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfGetRequestResponse_(soap, _param_22);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfGetRequestResponse_(soap, _param_22, "srm2:srmStatusOfGetRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmBringOnline(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmBringOnlineRequest *srmBringOnlineRequest, struct srm2__srmBringOnlineResponse_ *_param_23)
{	struct srm2__srmBringOnline soap_tmp_srm2__srmBringOnline;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmBringOnline.srmBringOnlineRequest = srmBringOnlineRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmBringOnline(soap, &soap_tmp_srm2__srmBringOnline);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmBringOnline(soap, &soap_tmp_srm2__srmBringOnline, "srm2:srmBringOnline", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmBringOnline(soap, &soap_tmp_srm2__srmBringOnline, "srm2:srmBringOnline", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmBringOnlineResponse_(soap, _param_23);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmBringOnlineResponse_(soap, _param_23, "srm2:srmBringOnlineResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfBringOnlineRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfBringOnlineRequestRequest *srmStatusOfBringOnlineRequestRequest, struct srm2__srmStatusOfBringOnlineRequestResponse_ *_param_24)
{	struct srm2__srmStatusOfBringOnlineRequest soap_tmp_srm2__srmStatusOfBringOnlineRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfBringOnlineRequest.srmStatusOfBringOnlineRequestRequest = srmStatusOfBringOnlineRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfBringOnlineRequest(soap, &soap_tmp_srm2__srmStatusOfBringOnlineRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfBringOnlineRequest(soap, &soap_tmp_srm2__srmStatusOfBringOnlineRequest, "srm2:srmStatusOfBringOnlineRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfBringOnlineRequest(soap, &soap_tmp_srm2__srmStatusOfBringOnlineRequest, "srm2:srmStatusOfBringOnlineRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfBringOnlineRequestResponse_(soap, _param_24);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfBringOnlineRequestResponse_(soap, _param_24, "srm2:srmStatusOfBringOnlineRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmPrepareToPut(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmPrepareToPutRequest *srmPrepareToPutRequest, struct srm2__srmPrepareToPutResponse_ *_param_25)
{	struct srm2__srmPrepareToPut soap_tmp_srm2__srmPrepareToPut;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmPrepareToPut.srmPrepareToPutRequest = srmPrepareToPutRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPrepareToPut(soap, &soap_tmp_srm2__srmPrepareToPut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmPrepareToPut(soap, &soap_tmp_srm2__srmPrepareToPut, "srm2:srmPrepareToPut", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPrepareToPut(soap, &soap_tmp_srm2__srmPrepareToPut, "srm2:srmPrepareToPut", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmPrepareToPutResponse_(soap, _param_25);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmPrepareToPutResponse_(soap, _param_25, "srm2:srmPrepareToPutResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfPutRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfPutRequestRequest *srmStatusOfPutRequestRequest, struct srm2__srmStatusOfPutRequestResponse_ *_param_26)
{	struct srm2__srmStatusOfPutRequest soap_tmp_srm2__srmStatusOfPutRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfPutRequest.srmStatusOfPutRequestRequest = srmStatusOfPutRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfPutRequest(soap, &soap_tmp_srm2__srmStatusOfPutRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfPutRequest(soap, &soap_tmp_srm2__srmStatusOfPutRequest, "srm2:srmStatusOfPutRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfPutRequest(soap, &soap_tmp_srm2__srmStatusOfPutRequest, "srm2:srmStatusOfPutRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfPutRequestResponse_(soap, _param_26);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfPutRequestResponse_(soap, _param_26, "srm2:srmStatusOfPutRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmCopy(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmCopyRequest *srmCopyRequest, struct srm2__srmCopyResponse_ *_param_27)
{	struct srm2__srmCopy soap_tmp_srm2__srmCopy;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmCopy.srmCopyRequest = srmCopyRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmCopy(soap, &soap_tmp_srm2__srmCopy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmCopy(soap, &soap_tmp_srm2__srmCopy, "srm2:srmCopy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmCopy(soap, &soap_tmp_srm2__srmCopy, "srm2:srmCopy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmCopyResponse_(soap, _param_27);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmCopyResponse_(soap, _param_27, "srm2:srmCopyResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmStatusOfCopyRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmStatusOfCopyRequestRequest *srmStatusOfCopyRequestRequest, struct srm2__srmStatusOfCopyRequestResponse_ *_param_28)
{	struct srm2__srmStatusOfCopyRequest soap_tmp_srm2__srmStatusOfCopyRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmStatusOfCopyRequest.srmStatusOfCopyRequestRequest = srmStatusOfCopyRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfCopyRequest(soap, &soap_tmp_srm2__srmStatusOfCopyRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmStatusOfCopyRequest(soap, &soap_tmp_srm2__srmStatusOfCopyRequest, "srm2:srmStatusOfCopyRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfCopyRequest(soap, &soap_tmp_srm2__srmStatusOfCopyRequest, "srm2:srmStatusOfCopyRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmStatusOfCopyRequestResponse_(soap, _param_28);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmStatusOfCopyRequestResponse_(soap, _param_28, "srm2:srmStatusOfCopyRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmReleaseFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmReleaseFilesRequest *srmReleaseFilesRequest, struct srm2__srmReleaseFilesResponse_ *_param_29)
{	struct srm2__srmReleaseFiles soap_tmp_srm2__srmReleaseFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmReleaseFiles.srmReleaseFilesRequest = srmReleaseFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReleaseFiles(soap, &soap_tmp_srm2__srmReleaseFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmReleaseFiles(soap, &soap_tmp_srm2__srmReleaseFiles, "srm2:srmReleaseFiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReleaseFiles(soap, &soap_tmp_srm2__srmReleaseFiles, "srm2:srmReleaseFiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmReleaseFilesResponse_(soap, _param_29);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmReleaseFilesResponse_(soap, _param_29, "srm2:srmReleaseFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmPutDone(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmPutDoneRequest *srmPutDoneRequest, struct srm2__srmPutDoneResponse_ *_param_30)
{	struct srm2__srmPutDone soap_tmp_srm2__srmPutDone;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmPutDone.srmPutDoneRequest = srmPutDoneRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPutDone(soap, &soap_tmp_srm2__srmPutDone);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmPutDone(soap, &soap_tmp_srm2__srmPutDone, "srm2:srmPutDone", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPutDone(soap, &soap_tmp_srm2__srmPutDone, "srm2:srmPutDone", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmPutDoneResponse_(soap, _param_30);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmPutDoneResponse_(soap, _param_30, "srm2:srmPutDoneResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmAbortRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmAbortRequestRequest *srmAbortRequestRequest, struct srm2__srmAbortRequestResponse_ *_param_31)
{	struct srm2__srmAbortRequest soap_tmp_srm2__srmAbortRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmAbortRequest.srmAbortRequestRequest = srmAbortRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmAbortRequest(soap, &soap_tmp_srm2__srmAbortRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmAbortRequest(soap, &soap_tmp_srm2__srmAbortRequest, "srm2:srmAbortRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmAbortRequest(soap, &soap_tmp_srm2__srmAbortRequest, "srm2:srmAbortRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmAbortRequestResponse_(soap, _param_31);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmAbortRequestResponse_(soap, _param_31, "srm2:srmAbortRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmAbortFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmAbortFilesRequest *srmAbortFilesRequest, struct srm2__srmAbortFilesResponse_ *_param_32)
{	struct srm2__srmAbortFiles soap_tmp_srm2__srmAbortFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmAbortFiles.srmAbortFilesRequest = srmAbortFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmAbortFiles(soap, &soap_tmp_srm2__srmAbortFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmAbortFiles(soap, &soap_tmp_srm2__srmAbortFiles, "srm2:srmAbortFiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmAbortFiles(soap, &soap_tmp_srm2__srmAbortFiles, "srm2:srmAbortFiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmAbortFilesResponse_(soap, _param_32);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmAbortFilesResponse_(soap, _param_32, "srm2:srmAbortFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmSuspendRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmSuspendRequestRequest *srmSuspendRequestRequest, struct srm2__srmSuspendRequestResponse_ *_param_33)
{	struct srm2__srmSuspendRequest soap_tmp_srm2__srmSuspendRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmSuspendRequest.srmSuspendRequestRequest = srmSuspendRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmSuspendRequest(soap, &soap_tmp_srm2__srmSuspendRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmSuspendRequest(soap, &soap_tmp_srm2__srmSuspendRequest, "srm2:srmSuspendRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmSuspendRequest(soap, &soap_tmp_srm2__srmSuspendRequest, "srm2:srmSuspendRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmSuspendRequestResponse_(soap, _param_33);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmSuspendRequestResponse_(soap, _param_33, "srm2:srmSuspendRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmResumeRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmResumeRequestRequest *srmResumeRequestRequest, struct srm2__srmResumeRequestResponse_ *_param_34)
{	struct srm2__srmResumeRequest soap_tmp_srm2__srmResumeRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmResumeRequest.srmResumeRequestRequest = srmResumeRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmResumeRequest(soap, &soap_tmp_srm2__srmResumeRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmResumeRequest(soap, &soap_tmp_srm2__srmResumeRequest, "srm2:srmResumeRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmResumeRequest(soap, &soap_tmp_srm2__srmResumeRequest, "srm2:srmResumeRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmResumeRequestResponse_(soap, _param_34);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmResumeRequestResponse_(soap, _param_34, "srm2:srmResumeRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetRequestSummary(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetRequestSummaryRequest *srmGetRequestSummaryRequest, struct srm2__srmGetRequestSummaryResponse_ *_param_35)
{	struct srm2__srmGetRequestSummary soap_tmp_srm2__srmGetRequestSummary;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetRequestSummary.srmGetRequestSummaryRequest = srmGetRequestSummaryRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetRequestSummary(soap, &soap_tmp_srm2__srmGetRequestSummary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetRequestSummary(soap, &soap_tmp_srm2__srmGetRequestSummary, "srm2:srmGetRequestSummary", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetRequestSummary(soap, &soap_tmp_srm2__srmGetRequestSummary, "srm2:srmGetRequestSummary", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetRequestSummaryResponse_(soap, _param_35);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetRequestSummaryResponse_(soap, _param_35, "srm2:srmGetRequestSummaryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmExtendFileLifeTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmExtendFileLifeTimeRequest *srmExtendFileLifeTimeRequest, struct srm2__srmExtendFileLifeTimeResponse_ *_param_36)
{	struct srm2__srmExtendFileLifeTime soap_tmp_srm2__srmExtendFileLifeTime;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmExtendFileLifeTime.srmExtendFileLifeTimeRequest = srmExtendFileLifeTimeRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmExtendFileLifeTime(soap, &soap_tmp_srm2__srmExtendFileLifeTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmExtendFileLifeTime(soap, &soap_tmp_srm2__srmExtendFileLifeTime, "srm2:srmExtendFileLifeTime", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmExtendFileLifeTime(soap, &soap_tmp_srm2__srmExtendFileLifeTime, "srm2:srmExtendFileLifeTime", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmExtendFileLifeTimeResponse_(soap, _param_36);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmExtendFileLifeTimeResponse_(soap, _param_36, "srm2:srmExtendFileLifeTimeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetRequestTokens(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetRequestTokensRequest *srmGetRequestTokensRequest, struct srm2__srmGetRequestTokensResponse_ *_param_37)
{	struct srm2__srmGetRequestTokens soap_tmp_srm2__srmGetRequestTokens;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetRequestTokens.srmGetRequestTokensRequest = srmGetRequestTokensRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetRequestTokens(soap, &soap_tmp_srm2__srmGetRequestTokens);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetRequestTokens(soap, &soap_tmp_srm2__srmGetRequestTokens, "srm2:srmGetRequestTokens", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetRequestTokens(soap, &soap_tmp_srm2__srmGetRequestTokens, "srm2:srmGetRequestTokens", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetRequestTokensResponse_(soap, _param_37);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetRequestTokensResponse_(soap, _param_37, "srm2:srmGetRequestTokensResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmGetTransferProtocols(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmGetTransferProtocolsRequest *srmGetTransferProtocolsRequest, struct srm2__srmGetTransferProtocolsResponse_ *_param_38)
{	struct srm2__srmGetTransferProtocols soap_tmp_srm2__srmGetTransferProtocols;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmGetTransferProtocols.srmGetTransferProtocolsRequest = srmGetTransferProtocolsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetTransferProtocols(soap, &soap_tmp_srm2__srmGetTransferProtocols);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmGetTransferProtocols(soap, &soap_tmp_srm2__srmGetTransferProtocols, "srm2:srmGetTransferProtocols", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetTransferProtocols(soap, &soap_tmp_srm2__srmGetTransferProtocols, "srm2:srmGetTransferProtocols", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmGetTransferProtocolsResponse_(soap, _param_38);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmGetTransferProtocolsResponse_(soap, _param_38, "srm2:srmGetTransferProtocolsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_srm2__srmPing(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct srm2__srmPingRequest *srmPingRequest, struct srm2__srmPingResponse_ *_param_39)
{	struct srm2__srmPing soap_tmp_srm2__srmPing;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_srm2__srmPing.srmPingRequest = srmPingRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPing(soap, &soap_tmp_srm2__srmPing);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_srm2__srmPing(soap, &soap_tmp_srm2__srmPing, "srm2:srmPing", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPing(soap, &soap_tmp_srm2__srmPing, "srm2:srmPing", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_srm2__srmPingResponse_(soap, _param_39);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_srm2__srmPingResponse_(soap, _param_39, "srm2:srmPingResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of srmv2Client.c */
